#theme: jekyll-theme-slate
theme: jekyll-theme-cayman
title: [A peek at Covid's impact on physical and mental health through digital footprints]
description: [Explore the relationship among pageviews,moblity and covid data.]

navigation:
  - title: Home
    url: /
#   - title: content
#     url: content
